#!/bin/bash
echo "Testing custom domain configuration..."
echo ""
echo "Frontend: https://moylakothai.xyz"
echo "Backend API: https://api.moylakothai.xyz"
echo ""
echo "Testing backend API..."
curl -s -o /dev/null -w "HTTP Status: %{http_code}\n" https://api.moylakothai.xyz/api/health || echo "Backend not ready yet"
echo ""
echo "Testing frontend..."
curl -s -o /dev/null -w "HTTP Status: %{http_code}\n" https://moylakothai.xyz || echo "Frontend not ready yet"
echo ""
echo "If you see HTTP 200, your domain is working!"
echo "If you see errors, DNS is still propagating (wait 5-60 minutes)"
